$bg = {{colors.background.default.hex_stripped}}
$surface = {{colors.surface.default.hex_stripped}}
$overlay = {{colors.surface_variant.default.hex_stripped}}
$text = {{colors.on_surface.default.hex_stripped}}
$subtext = {{colors.on_surface_variant.default.hex_stripped}}
$primary = {{colors.primary.default.hex_stripped}}
$error = {{colors.error.default.hex_stripped}}
$border_active = rgba({{colors.primary.default.hex_stripped}}ff)
$border_inactive = rgba({{colors.surface_variant.default.hex_stripped}}ff)
$rounding = 12
$border_size = 2
$gaps_in = 4
$gaps_out = 8
$blur_size = 4
$blur_passes = 2
$blur_vibrancy = 0.0
$inactive_opacity = 0.90
$shadow_color = rgba(00000000)
