background            #fafafa
foreground            #333333
selection_background  #a3b8cc
selection_foreground  #fafafa
cursor                #a3b8cc
cursor_text_color     #fafafa
color0   #e5e5e5
color8   #666666
color1   #e57373
color9   #e57373
color2   #a3b8cc
color10  #a3b8cc
color3   #333333
color11  #333333
color4   #a3b8cc
color12  #a3b8cc
color5   #a3b8cc
color13  #a3b8cc
color6   #a3b8cc
color14  #a3b8cc
color7   #333333
color15  #333333
url_color #a3b8cc
active_tab_background   #a3b8cc
active_tab_foreground   #fafafa
inactive_tab_background #f0f0f0
inactive_tab_foreground #333333
