background            #1a0f0f
foreground            #f2d9d9
selection_background  #cc4343
selection_foreground  #1a0f0f
cursor                #cc4343
cursor_text_color     #1a0f0f
color0   #0d0707
color8   #b38c8c
color1   #ff4d4d
color9   #ff4d4d
color2   #cc4343
color10  #cc4343
color3   #f2d9d9
color11  #f2d9d9
color4   #cc4343
color12  #cc4343
color5   #cc4343
color13  #cc4343
color6   #cc4343
color14  #cc4343
color7   #f2d9d9
color15  #f2d9d9
url_color #cc4343
active_tab_background   #cc4343
active_tab_foreground   #1a0f0f
inactive_tab_background #261717
inactive_tab_foreground #f2d9d9
