background            #282828
foreground            #ebdbb2
selection_background  #d79921
selection_foreground  #282828
cursor                #d79921
cursor_text_color     #282828
color0   #1d2021
color8   #a89984
color1   #cc241d
color9   #cc241d
color2   #d79921
color10  #d79921
color3   #ebdbb2
color11  #ebdbb2
color4   #d79921
color12  #d79921
color5   #d79921
color13  #d79921
color6   #d79921
color14  #d79921
color7   #ebdbb2
color15  #ebdbb2
url_color #d79921
active_tab_background   #d79921
active_tab_foreground   #282828
inactive_tab_background #3c3836
inactive_tab_foreground #ebdbb2
