background            #1a1525
foreground            #e6d9f2
selection_background  #a37acc
selection_foreground  #1a1525
cursor                #a37acc
cursor_text_color     #1a1525
color0   #120e1a
color8   #a693bf
color1   #ff6699
color9   #ff6699
color2   #a37acc
color10  #a37acc
color3   #e6d9f2
color11  #e6d9f2
color4   #a37acc
color12  #a37acc
color5   #a37acc
color13  #a37acc
color6   #a37acc
color14  #a37acc
color7   #e6d9f2
color15  #e6d9f2
url_color #a37acc
active_tab_background   #a37acc
active_tab_foreground   #1a1525
inactive_tab_background #221b33
inactive_tab_foreground #e6d9f2
