background            #131318
foreground            #e4e1e9
selection_background  #c2c1ff
selection_foreground  #131318
cursor                #c2c1ff
cursor_text_color     #131318
color0   #47464f
color8   #c8c5d0
color1   #ffb4ab
color9   #ffb4ab
color2   #c2c1ff
color10  #c2c1ff
color3   #c6c4dd
color11  #c6c4dd
color4   #c2c1ff
color12  #c2c1ff
color5   #e9b9d2
color13  #e9b9d2
color6   #c2c1ff
color14  #c2c1ff
color7   #e4e1e9
color15  #e4e1e9
url_color #c2c1ff
active_tab_background   #c2c1ff
active_tab_foreground   #131318
inactive_tab_background #131318
inactive_tab_foreground #e4e1e9
