background            #2e3440
foreground            #d8dee9
selection_background  #88c0d0
selection_foreground  #2e3440
cursor                #88c0d0
cursor_text_color     #2e3440
color0   #242933
color8   #e5e9f0
color1   #bf616a
color9   #bf616a
color2   #88c0d0
color10  #88c0d0
color3   #d8dee9
color11  #d8dee9
color4   #88c0d0
color12  #88c0d0
color5   #88c0d0
color13  #88c0d0
color6   #88c0d0
color14  #88c0d0
color7   #d8dee9
color15  #d8dee9
url_color #88c0d0
active_tab_background   #88c0d0
active_tab_foreground   #2e3440
inactive_tab_background #3b4252
inactive_tab_foreground #d8dee9
