background            #1a1b26
foreground            #c0caf5
selection_background  #7aa2f7
selection_foreground  #1a1b26
cursor                #7aa2f7
cursor_text_color     #1a1b26
color0   #15161e
color8   #a9b1d6
color1   #f7768e
color9   #f7768e
color2   #7aa2f7
color10  #7aa2f7
color3   #c0caf5
color11  #c0caf5
color4   #7aa2f7
color12  #7aa2f7
color5   #7aa2f7
color13  #7aa2f7
color6   #7aa2f7
color14  #7aa2f7
color7   #c0caf5
color15  #c0caf5
url_color #7aa2f7
active_tab_background   #7aa2f7
active_tab_foreground   #1a1b26
inactive_tab_background #1f2335
inactive_tab_foreground #c0caf5
