[urgency_low]
    background  = "#26253a"
    foreground  = "#f1f5f9"
    frame_color = "#312f47"
    timeout     = 4
    default_icon = dialog-information

[urgency_normal]
    background  = "#26253a"
    foreground  = "#f1f5f9"
    frame_color = "#333333"
    timeout     = 6
    default_icon = dialog-information

[urgency_critical]
    background  = "#26253a"
    foreground  = "#fb7185"
    frame_color = "#fb7185"
    timeout     = 0
    default_icon = dialog-warning
