[urgency_low]
    background  = "#161b22"
    foreground  = "#e6edf3"
    frame_color = "#21262d"
    timeout     = 4
    default_icon = dialog-information

[urgency_normal]
    background  = "#161b22"
    foreground  = "#e6edf3"
    frame_color = "#333333"
    timeout     = 6
    default_icon = dialog-information

[urgency_critical]
    background  = "#161b22"
    foreground  = "#ff7b72"
    frame_color = "#ff7b72"
    timeout     = 0
    default_icon = dialog-warning
