$bg = {background.strip}
$surface = {color0.strip}
$overlay = {color8.strip}
$border_active = rgba({color4.strip}ff)
$border_inactive = rgba({color0.strip}ff)
$rounding = 12
$border_size = 2
$gaps_in = 4
$gaps_out = 8
$blur_size = 4
$blur_passes = 2
$blur_vibrancy = 0.0
$inactive_opacity = 0.90
$shadow_color = rgba(00000000)
