background            #1e1e2e
foreground            #cdd6f4
selection_background  #cba6f7
selection_foreground  #1e1e2e
cursor                #cba6f7
cursor_text_color     #1e1e2e
color0   #11111b
color8   #a6adc8
color1   #f38ba8
color9   #f38ba8
color2   #cba6f7
color10  #cba6f7
color3   #cdd6f4
color11  #cdd6f4
color4   #cba6f7
color12  #cba6f7
color5   #cba6f7
color13  #cba6f7
color6   #cba6f7
color14  #cba6f7
color7   #cdd6f4
color15  #cdd6f4
url_color #cba6f7
active_tab_background   #cba6f7
active_tab_foreground   #1e1e2e
inactive_tab_background #181825
inactive_tab_foreground #cdd6f4
