background            #15180a
foreground            #c4c5c1
selection_background  #90AA22
selection_foreground  #15180a
cursor                #90AA22
cursor_text_color     #15180a
color0   #15180a
color8   #696d59
color1   #896D41
color9   #896D41
color2   #5D9311
color10  #5D9311
color3   #649633
color11  #649633
color4   #90AA22
color12  #90AA22
color5   #9D9A5B
color13  #9D9A5B
color6   #BDD742
color14  #BDD742
color7   #c4c5c1
color15  #c4c5c1
url_color #90AA22
active_tab_background   #90AA22
active_tab_foreground   #15180a
inactive_tab_background #15180a
inactive_tab_foreground #c4c5c1
