background            #1a0033
foreground            #e6ccff
selection_background  #73e600
selection_foreground  #1a0033
cursor                #73e600
cursor_text_color     #1a0033
color0   #0d001a
color8   #9933ff
color1   #ff3300
color9   #ff3300
color2   #73e600
color10  #73e600
color3   #e6ccff
color11  #e6ccff
color4   #73e600
color12  #73e600
color5   #73e600
color13  #73e600
color6   #73e600
color14  #73e600
color7   #e6ccff
color15  #e6ccff
url_color #73e600
active_tab_background   #73e600
active_tab_foreground   #1a0033
inactive_tab_background #26004d
inactive_tab_foreground #e6ccff
