background            #0f0f0f
foreground            #cccccc
selection_background  #838996
selection_foreground  #0f0f0f
cursor                #838996
cursor_text_color     #0f0f0f
color0   #1a1a1a
color8   #888888
color1   #d75f5f
color9   #d75f5f
color2   #838996
color10  #838996
color3   #cccccc
color11  #cccccc
color4   #838996
color12  #838996
color5   #838996
color13  #838996
color6   #838996
color14  #838996
color7   #cccccc
color15  #cccccc
url_color #838996
active_tab_background   #838996
active_tab_foreground   #0f0f0f
inactive_tab_background #141414
inactive_tab_foreground #cccccc
