background            #0f1715
foreground            #e2f3eb
selection_background  #1db954
selection_foreground  #0f1715
cursor                #1db954
cursor_text_color     #0f1715
color0   #080c0b
color8   #a3c9b9
color1   #e05252
color9   #e05252
color2   #1db954
color10  #1db954
color3   #e2f3eb
color11  #e2f3eb
color4   #1db954
color12  #1db954
color5   #1db954
color13  #1db954
color6   #1db954
color14  #1db954
color7   #e2f3eb
color15  #e2f3eb
url_color #1db954
active_tab_background   #1db954
active_tab_foreground   #0f1715
inactive_tab_background #18221f
inactive_tab_foreground #e2f3eb
