-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

bg = "1e1e2e"

surface = "181825"

overlay = "11111b"

border_active = "rgba(cba6f7ff)"

border_inactive = "rgba(313244ff)"

rounding = 12

border_size = 2

gaps_in = 4

gaps_out = 8

blur_size = 4

blur_passes = 2

blur_vibrancy = 0.0

inactive_opacity = 0.90

shadow_color = "rgba(00000000)"
