$bg = 1a0033
$surface = 26004d
$overlay = 0d001a
$border_active = rgba(73e600ff)
$border_inactive = rgba(390073ff)
$rounding = 12
$border_size = 2
$gaps_in = 4
$gaps_out = 8
$blur_size = 4
$blur_passes = 2
$blur_vibrancy = 0.0
$inactive_opacity = 0.90
$shadow_color = rgba(00000000)
