$bg = 0f1715
$surface = 18221f
$overlay = 080c0b
$border_active = rgba(1db954ff)
$border_inactive = rgba(253631ff)
$rounding = 12
$border_size = 2
$gaps_in = 4
$gaps_out = 8
$blur_size = 4
$blur_passes = 2
$blur_vibrancy = 0.0
$inactive_opacity = 0.90
$shadow_color = rgba(00000000)
