-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

bg = "1a1b26"

surface = "1f2335"

overlay = "15161e"

border_active = "rgba(7aa2f7ff)"

border_inactive = "rgba(292e42ff)"

rounding = 12

border_size = 2

gaps_in = 4

gaps_out = 8

blur_size = 4

blur_passes = 2

blur_vibrancy = 0.0

inactive_opacity = 0.90

shadow_color = "rgba(00000000)"
