source = ~/.config/hypr/themes/current_theme.conf
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/general.conf
source = ~/.config/hypr/modules/decorations.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/exec.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/windowrules.conf
source = ~/.config/hypr/modules/workspaces.conf

# Overrides from Quickshell GUI
source = ~/.config/hypr/overrides.conf
