animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = easeOut, 0.16, 1, 0.3, 1
    bezier = linear, 0, 0, 1, 1
    bezier = snappy, 0.68, -0.55, 0.27, 1.55
    bezier = overshot, 0.13, 0.99, 0.29, 1.1

    animation = windows, 1, 5, myBezier
    animation = windowsOut, 1, 4, easeOut, popin 80%
    animation = windowsMove, 1, 5, myBezier
    animation = fade, 1, 5, easeOut
    animation = fadeIn, 1, 5, easeOut
    animation = fadeOut, 1, 4, easeOut
    animation = fadeSwitch, 1, 5, easeOut
    animation = fadeShadow, 1, 5, easeOut
    animation = fadeDim, 1, 5, easeOut
    animation = workspaces, 1, 6, myBezier, slide
    animation = specialWorkspace, 1, 5, myBezier, slidevert
    animation = border, 1, 8, linear
    animation = borderangle, 1, 80, linear, loop
    animation = layers, 1, 4, easeOut, slide top
}
