-- ══════════════════════════════════════════════════════════════
-- HyprZen — Window Rules (Hyprland 0.55+)
-- ══════════════════════════════════════════════════════════════

-- ── Floating apps ─────────────────────────────────────────────
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(hyprland-share-picker)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal-hyprland)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    match = {
        class = "^(thunar)$",
    },
    float = true,
    center = true,
    size = "920 600",
})

hl.window_rule({
    match = {
        class = "^(com\\.gabm\\.satty)$",
    },
    float = true,
    center = true,
    size = "1200 800",
})

hl.window_rule({
    match = {
        class = "^(org\\.gnome\\.Nautilus)$",
    },
    float = true,
    center = true,
    size = "920 600",
})

hl.window_rule({
    match = {
        class = "^(pavucontrol)$",
    },
    float = true,
    center = true,
    size = "720 500",
})

hl.window_rule({
    match = {
        class = "^(org\\.pulseaudio\\.pavucontrol)$",
    },
    float = true,
    center = true,
    size = "720 500",
})

hl.window_rule({
    match = {
        class = "^(impala)$",
    },
    float = true,
    center = true,
    size = "640 480",
})

hl.window_rule({
    match = {
        class = "^(org\\.gnome\\.Calculator)$",
    },
    float = true,
    center = true,
    size = "380 520",
})

hl.window_rule({
    match = {
        class = "^(imv)$",
    },
    float = true,
    center = true,
    size = "900 700",
})

hl.window_rule({
    match = {
        class = "^(mpv)$",
    },
    float = true,
    center = true,
    size = "1280 720",
})

-- ── Rofi ──────────────────────────────────────────────────────
hl.window_rule({
    match = {
        class = "^(Rofi)$",
    },
    float = true,
    center = true,
})

-- ── Wlogout ───────────────────────────────────────────────────
hl.window_rule({
    match = {
        class = "^(wlogout)$",
    },
    float = true,
    center = true,
})

-- ── Picture-in-Picture ────────────────────────────────────────
hl.window_rule({
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
    pin = true,
    move = "73% 72%",
    size = "25% 25%",
})

-- ── Opacity ───────────────────────────────────────────────────
hl.window_rule({
    match = {
        class = "^(kitty)$",
    },
    opacity = "0.92 0.85",
})

hl.window_rule({
    match = {
        class = "^(discord)$",
    },
    opacity = "0.95 0.90",
})

hl.window_rule({
    match = {
        class = "^(thunar)$",
    },
    opacity = "0.95 0.90",
})

hl.window_rule({
    match = {
        class = "^(obsidian)$",
    },
    opacity = "0.92 0.88",
})

hl.window_rule({
    match = {
        class = "^(org\\.telegram\\.desktop)$",
    },
    opacity = "0.95 0.90",
})

hl.window_rule({
    match = {
        class = "^(Code)$",
    },
    opacity = "0.90 0.85",
})

hl.window_rule({
    match = {
        class = "^(vscodium)$",
    },
    opacity = "0.90 0.85",
})

hl.window_rule({
    match = {
        class = "^(codium)$",
    },
    opacity = "0.90 0.85",
})

hl.window_rule({
    match = {
        class = "^(antigravity)$",
    },
    opacity = "0.90 0.85",
})

hl.window_rule({
    match = {
        class = "^(AntiGravity)$",
    },
    opacity = "0.90 0.85",
})

hl.window_rule({
    match = {
        class = "^(jetbrains-studio)$",
    },
    opacity = "0.90 0.85",
})

hl.window_rule({
    match = {
        class = "^(Android Studio)$",
    },
    opacity = "0.90 0.85",
})

hl.window_rule({
    match = {
        class = "^(librewolf)$",
    },
    opacity = "0.90 0.85",
})

-- ── Force tile ────────────────────────────────────────────────
hl.window_rule({
    match = {
        class = "^(Spotify)$",
    },
    float = false,
})

hl.window_rule({
    match = {
        class = "^(steam)$",
    },
    float = false,
})

hl.window_rule({
    match = {
        class = "^(lutris)$",
    },
    float = false,
})

-- ── Steam popups ──────────────────────────────────────────────
hl.window_rule({
    match = {
        class = "^(steam)$",
        title = "^(Friends List)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(steam)$",
        title = "^(Steam Settings)$",
    },
    float = true,
    center = true,
    size = "940 720",
})

-- ── Idle Inhibit ─────────────────────────────────────────────
hl.window_rule({
    match = {
        class = "^(mpv)$",
    },
    idle_inhibit = "focus",
})

hl.window_rule({
    match = {
        class = "^(firefox)$",
    },
    idle_inhibit = "fullscreen",
})

-- ── Layer Rules ───────────────────────────────────────────────
-- Waybar
hl.layer_rule({
    match = { namespace = "^(waybar)$" },
    blur = true,
    ignore_alpha = 0.5,
})

-- SwayNC notifications
hl.layer_rule({
    match = { namespace = "^(swaync-notification-window)$" },
    blur = true,
    ignore_alpha = 0.1,
})

-- SwayNC control center
hl.layer_rule({
    match = { namespace = "^(swaync-control-center)$" },
    blur = true,
    ignore_alpha = 0.1,
})

-- Rofi
hl.layer_rule({
    match = { namespace = "^(rofi)$" },
    blur = true,
    ignore_alpha = 0.1,
})

-- Hyprswitch
hl.layer_rule({
    match = { namespace = "^(hyprswitch)$" },
    blur = true,
    ignore_alpha = 0.1,
})

-- Wlogout
hl.layer_rule({
    match = { namespace = "^(logout_dialog)$" },
    blur = true,
    ignore_alpha = 0.2,
})

hl.layer_rule({
    match = { namespace = "^(wlogout)$" },
    blur = true,
    ignore_alpha = 0.2,
})

-- ── Quickshell Wallpaper Picker ───────────────────────────────

-- ── Quickshell Wallpaper Picker ───────────────────────────────
hl.window_rule({
    match = {
        title = "^(wallpaper-picker)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    match = {
        class = "^(quickshell)$",
    },
    float = true,
    center = true,
})
