-- ══════════════════════════════════════════════════════════════
-- HyprZen — Workspaces
-- Plain numbered workspaces — names shown in waybar as 1-8
-- ══════════════════════════════════════════════════════════════

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.workspace_rule({
    workspace = "1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "2",
    persistent = true,
})

hl.workspace_rule({
    workspace = "3",
    persistent = true,
})

hl.workspace_rule({
    workspace = "4",
    persistent = true,
})

hl.workspace_rule({
    workspace = "special:magic",
    gaps_in = 30,
    gaps_out = 60,
    no_border = 1,
})

-- ── App → Workspace rules ─────────────────────────────────────
hl.window_rule({
    match = {
        class = "^(firefox)$",
    },
    workspace = "2 silent",
})

hl.window_rule({
    match = {
        class = "^(chromium)$",
    },
    workspace = "2 silent",
})

hl.window_rule({
    match = {
        class = "^(zen-browser)$",
    },
    workspace = "2 silent",
})

hl.window_rule({
    match = {
        class = "^(Code)$",
    },
    workspace = "3 silent",
})

hl.window_rule({
    match = {
        class = "^(VSCodium)$",
    },
    workspace = "3 silent",
})

hl.window_rule({
    match = {
        class = "^(discord)$",
    },
    workspace = "4 silent",
})

hl.window_rule({
    match = {
        class = "^(org\\.telegram\\.desktop)$",
    },
    workspace = "4 silent",
})

hl.window_rule({
    match = {
        class = "^(Spotify)$",
    },
    workspace = "4 silent",
})

hl.window_rule({
    match = {
        class = "^(mpv)$",
    },
    workspace = "4 silent",
})

hl.window_rule({
    match = {
        class = "^(thunar)$",
    },
    workspace = "3 silent",
})

hl.window_rule({
    match = {
        class = "^(steam)$",
    },
    workspace = "4 silent",
})

hl.window_rule({
    match = {
        class = "^(lutris)$",
    },
    workspace = "4 silent",
})
