-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

bg = "1a0f0f"

surface = "261717"

overlay = "0d0707"

border_active = "rgba(cc4343ff)"

border_inactive = "rgba(402626ff)"

rounding = 12

border_size = 2

gaps_in = 4

gaps_out = 8

blur_size = 4

blur_passes = 2

blur_vibrancy = 0.0

inactive_opacity = 0.90

shadow_color = "rgba(00000000)"
